image: node:5

cache:
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  script:
   - npm install
   - npm run test

image: node:6

cache:
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  script:
   - npm install
   - npm run test

image: node:7

cache:
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  script:
   - npm install
   - npm run test

image: node:8

cache:
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  script:
   - npm install
   - npm run test

image: node:9

cache:
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  script:
   - npm install
   - npm run test
